### ISSUE TITLE
Command 'awsr' not found

### ISSUE THREAD

**Issue by reka193** [janakaud/aws-cli-repl#2]
Hi! I have followed the two steps of the instruction (added to system path and made it executable), however, I am getting Command 'awsr' not found error. Can you please provide some info what could be the problem? Thanks!

**Comment by janakaud** [comment]
Hi @reka193!

Looks like the system path has not been configured properly.

Can you show the outputs of the following commands:

`which awsr`

`echo $PATH`

**Comment by reka193** [comment]
Problem solved, thank you for the help! :)
