### ISSUE TITLE
Using query fails

### ISSUE THREAD

**Issue by matt-horwood-mayden** [janakaud/aws-cli-repl#22]
have now got a working setup, but get an error when running

in terminal 1 `export AWSR_DAEMON=True;./awsr` to have a server run
in terminal 2 `export AWSR_CLIENT=True; ../aws-cli-repl/awsr ec2 describe-instances --query 'Reservations[].Instances[].{Name: Tags[?Key==Name].Value | [0], ID: InstanceId, IP: PrivateIpAddress}'`

Then in terminal 1 I get an error
```
Bad value for --query Reservations[].Instances[].{Name:: Invalid jmespath expression: Incomplete expression:
"Reservations[].Instances[].{Name:"
                                  ^
```

**Comment by gaul** [comment]
aws-cli-repl sends command line arguments as a space-separated string:

```python
out.write(" ".join(sys.argv))
```

and decodes them by splitting:

```python
args = args.decode("utf-8").split(" ")[1:]
```

This cannot round-trip arguments with spaces.  As a workaround you can just remove the spaces from your input.  But we need some more complicated encoding and #5 suggests one alternative.
