### ISSUE TITLE
Command not executing at all (TypeError: object of type 'NoneType' has no len())

### ISSUE THREAD

**Issue by eheinen** [janakaud/aws-cli-repl#3]
Hi @janakaud,

I follow your instructions and when I run the command it always fails in the line 77 due to cmd being NoneType. Probably it is something pretty simple to solve.

My python version is `2.7.10`

```
awsr ec2 describe-instances
Traceback (most recent call last):
  File "/Users/.../awsr_dir/awsr", line 77, in <module>
    if len(cmd) > 1 and cmd[0].endswith("python") and cmd[1] == sys.argv[0]:
TypeError: object of type 'NoneType' has no len()
```

I tried to use zsh and bash, both have the same problem.

Thank you!

**Comment by max-rocket-internet** [comment]
You can fix it like this [at this line](https://github.com/janakaud/aws-cli-repl/blob/master/awsr#L77):

```diff
- 		if len(cmd) > 1 and cmd[0].endswith("python") and cmd[1] == sys.argv[0]:
+ 		if cmd and len(cmd) > 1 and cmd[0].endswith("python") and cmd[1] == sys.argv[0]:
```

**Comment by janakaud** [comment]
Hello @eheinen, thanks for raising this!

And thanks @max-rocket-internet for the fix! @eheinen can you confirm if the fix works for you?

**Comment by gaul** [comment]
Please reopen if the symptoms persist.
